package main

import "embed"

// nucleiTemplates embeds only the curated AI/LLM Nuclei templates used by the scanner.
//
//go:embed nuclei-templates/profiles/ai-llm.yaml
//go:embed nuclei-templates/http/cves/2014/CVE-2014-3120.yaml
//go:embed nuclei-templates/http/cves/2015/CVE-2015-1427.yaml
//go:embed nuclei-templates/http/cves/2015/CVE-2015-3337.yaml
//go:embed nuclei-templates/http/cves/2015/CVE-2015-5531.yaml
//go:embed nuclei-templates/http/cves/2016/CVE-2016-9299.yaml
//go:embed nuclei-templates/http/cves/2017/CVE-2017-12629.yaml
//go:embed nuclei-templates/http/cves/2018/CVE-2018-1000600.yaml
//go:embed nuclei-templates/http/cves/2018/CVE-2018-1000861.yaml
//go:embed nuclei-templates/http/cves/2018/CVE-2018-17246.yaml
//go:embed nuclei-templates/http/cves/2018/CVE-2018-8024.yaml
//go:embed nuclei-templates/http/cves/2019/CVE-2019-1003000.yaml
//go:embed nuclei-templates/http/cves/2019/CVE-2019-10405.yaml
//go:embed nuclei-templates/http/cves/2019/CVE-2019-10475.yaml
//go:embed nuclei-templates/http/cves/2019/CVE-2019-10758.yaml
//go:embed nuclei-templates/http/cves/2019/CVE-2019-15043.yaml
//go:embed nuclei-templates/http/cves/2019/CVE-2019-16097.yaml
//go:embed nuclei-templates/http/cves/2019/CVE-2019-6793.yaml
//go:embed nuclei-templates/http/cves/2019/CVE-2019-7609.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-11110.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-11978.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-13379.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-13927.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-16248.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-17526.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-2096.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-2103.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-2140.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-24391.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-26413.yaml
//go:embed nuclei-templates/http/cves/2020/CVE-2020-9480.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-21287.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-22145.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-22175.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-22205.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-22214.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-27358.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-29622.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-38540.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-39226.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-41174.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-41266.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-4191.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-43798.yaml
//go:embed nuclei-templates/http/cves/2021/CVE-2021-43831.yaml
//go:embed nuclei-templates/http/cves/2022/CVE-2022-0735.yaml
//go:embed nuclei-templates/http/cves/2022/CVE-2022-1162.yaml
//go:embed nuclei-templates/http/cves/2022/CVE-2022-2185.yaml
//go:embed nuclei-templates/http/cves/2022/CVE-2022-24288.yaml
//go:embed nuclei-templates/http/cves/2022/CVE-2022-26148.yaml
//go:embed nuclei-templates/http/cves/2022/CVE-2022-28508.yaml
//go:embed nuclei-templates/http/cves/2022/CVE-2022-33891.yaml
//go:embed nuclei-templates/http/cves/2022/CVE-2022-36883.yaml
//go:embed nuclei-templates/http/cves/2022/CVE-2022-40127.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-1177.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-2356.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-2780.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-2825.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-28432.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-3765.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-43472.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-48022.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-48023.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-51449.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-6018.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-6020.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-6021.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-6568.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-6831.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-6909.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-6977.yaml
//go:embed nuclei-templates/http/cves/2023/CVE-2023-7028.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-10908.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-11044.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-1183.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-12760.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-13221.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-1483.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-1561.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-1728.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-2928.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-31621.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-37032.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-3848.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-4325.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-4841.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-4940.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-5936.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-6095.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-6250.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-6587.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-6842.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-6845.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-8021.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-8181.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-8859.yaml
//go:embed nuclei-templates/http/cves/2024/CVE-2024-9264.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-11750.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-26319.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-31489.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-3248.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-3415.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-34291.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-4123.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-49596.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-56520.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-58434.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-59474.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-6197.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-63387.yaml
//go:embed nuclei-templates/http/cves/2025/CVE-2025-8943.yaml
//go:embed nuclei-templates/http/cves/2026/CVE-2026-0770.yaml
//go:embed nuclei-templates/http/cves/2026/CVE-2026-24477.yaml
//go:embed nuclei-templates/http/default-logins/apache/airflow-default-login.yaml
//go:embed nuclei-templates/http/default-logins/apache/airflow-v3-default-login.yaml
//go:embed nuclei-templates/http/default-logins/dataiku/dataiku-default-login.yaml
//go:embed nuclei-templates/http/default-logins/elasticsearch/elasticsearch-default-login.yaml
//go:embed nuclei-templates/http/default-logins/gitlab/gitlab-weak-login.yaml
//go:embed nuclei-templates/http/default-logins/grafana/grafana-default-login.yaml
//go:embed nuclei-templates/http/default-logins/harbor-registry-default-login.yaml
//go:embed nuclei-templates/http/default-logins/jenkins/jenkins-default.yaml
//go:embed nuclei-templates/http/default-logins/jupyterhub/jupyterhub-default-login.yaml
//go:embed nuclei-templates/http/default-logins/minio/minio-default-login.yaml
//go:embed nuclei-templates/http/default-logins/opensearch-default-login.yaml
//go:embed nuclei-templates/http/default-logins/openwebui/openwebui-default-login.yaml
//go:embed nuclei-templates/http/default-logins/redis/redis-commander-default-login.yaml
//go:embed nuclei-templates/http/exposed-panels/airflow-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/aws-opensearch-login.yaml
//go:embed nuclei-templates/http/exposed-panels/dataiku-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/dify-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/gitlab-detect.yaml
//go:embed nuclei-templates/http/exposed-panels/gitlab-explore.yaml
//go:embed nuclei-templates/http/exposed-panels/gitlab-saml.yaml
//go:embed nuclei-templates/http/exposed-panels/google-adk-api-exposed.yaml
//go:embed nuclei-templates/http/exposed-panels/google-adk-webui-exposed.yaml
//go:embed nuclei-templates/http/exposed-panels/grafana-detect.yaml
//go:embed nuclei-templates/http/exposed-panels/harbor-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/jenkins-api-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/jenkins-login.yaml
//go:embed nuclei-templates/http/exposed-panels/jupyter-notebook.yaml
//go:embed nuclei-templates/http/exposed-panels/kibana-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/minio-browser.yaml
//go:embed nuclei-templates/http/exposed-panels/minio-console.yaml
//go:embed nuclei-templates/http/exposed-panels/mongodb-ops-manager.yaml
//go:embed nuclei-templates/http/exposed-panels/neo4j-browser.yaml
//go:embed nuclei-templates/http/exposed-panels/ollama-llm-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/opensearch-dashboard-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/openwebui-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/portainer-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/privategpt-detect.yaml
//go:embed nuclei-templates/http/exposed-panels/prometheus-exposed-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/prometheus-pushgateway-exposed-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/redis-commander-exposure.yaml
//go:embed nuclei-templates/http/exposed-panels/redis-enterprise-panel.yaml
//go:embed nuclei-templates/http/exposed-panels/spark-panel.yaml
//go:embed nuclei-templates/http/misconfiguration/airflow/airflow-debug.yaml
//go:embed nuclei-templates/http/misconfiguration/airflow/unauthenticated-airflow.yaml
//go:embed nuclei-templates/http/misconfiguration/apache-spark-env.yaml
//go:embed nuclei-templates/http/misconfiguration/apachespark-ui-exposed.yaml
//go:embed nuclei-templates/http/misconfiguration/chroma-db-unauth.yaml
//go:embed nuclei-templates/http/misconfiguration/elasticsearch.yaml
//go:embed nuclei-templates/http/misconfiguration/exposed-kibana.yaml
//go:embed nuclei-templates/http/misconfiguration/flask-redis-docker.yaml
//go:embed nuclei-templates/http/misconfiguration/gitlab/gitlab-api-user-enum.yaml
//go:embed nuclei-templates/http/misconfiguration/gitlab/gitlab-public-repos.yaml
//go:embed nuclei-templates/http/misconfiguration/gitlab/gitlab-public-signup.yaml
//go:embed nuclei-templates/http/misconfiguration/gitlab/gitlab-public-snippets.yaml
//go:embed nuclei-templates/http/misconfiguration/gitlab/gitlab-uninitialized-password.yaml
//go:embed nuclei-templates/http/misconfiguration/gitlab/gitlab-user-enum.yaml
//go:embed nuclei-templates/http/misconfiguration/grafana-public-signup.yaml
//go:embed nuclei-templates/http/misconfiguration/grafana-unauth-access.yaml
//go:embed nuclei-templates/http/misconfiguration/installer/flowise-installer.yaml
//go:embed nuclei-templates/http/misconfiguration/jenkins/jenkins-openuser-register.yaml
//go:embed nuclei-templates/http/misconfiguration/jenkins/jenkins-users-exposure.yaml
//go:embed nuclei-templates/http/misconfiguration/jupyter-ipython-unauth.yaml
//go:embed nuclei-templates/http/misconfiguration/jupyter-lab-unauth.yaml
//go:embed nuclei-templates/http/misconfiguration/jupyter-notebooks-exposed.yaml
//go:embed nuclei-templates/http/misconfiguration/kubeflow-dashboard-unauth.yaml
//go:embed nuclei-templates/http/misconfiguration/mlflow-unauth.yaml
//go:embed nuclei-templates/http/misconfiguration/mongodb-exporter-metrics.yaml
//go:embed nuclei-templates/http/misconfiguration/mongodb-exposure.yaml
//go:embed nuclei-templates/http/misconfiguration/ollama-improper-authorization.yaml
//go:embed nuclei-templates/http/misconfiguration/opensearch-dashboard-unauth.yaml
//go:embed nuclei-templates/http/misconfiguration/prometheus-promtail.yaml
//go:embed nuclei-templates/http/misconfiguration/prometheus/prometheus-config.yaml
//go:embed nuclei-templates/http/misconfiguration/prometheus/prometheus-exporter.yaml
//go:embed nuclei-templates/http/misconfiguration/prometheus/prometheus-flags.yaml
//go:embed nuclei-templates/http/misconfiguration/prometheus/prometheus-log.yaml
//go:embed nuclei-templates/http/misconfiguration/prometheus/prometheus-targets.yaml
//go:embed nuclei-templates/http/misconfiguration/prometheus/prometheus-unauth.yaml
//go:embed nuclei-templates/http/misconfiguration/ray-dashboard.yaml
//go:embed nuclei-templates/http/misconfiguration/spark-webui-unauth.yaml
//go:embed nuclei-templates/http/misconfiguration/thanos-prometheus-exposure.yaml
//go:embed nuclei-templates/http/misconfiguration/unauth-qdrantui.yaml
//go:embed nuclei-templates/http/misconfiguration/unauth-redis-insight.yaml
//go:embed nuclei-templates/http/misconfiguration/unauthenticated-mongo-express.yaml
//go:embed nuclei-templates/http/misconfiguration/unauthenticated-tensorboard.yaml
//go:embed nuclei-templates/http/misconfiguration/weaviate-exposure.yaml
//go:embed nuclei-templates/http/vulnerabilities/bentoml-ssrf.yaml
//go:embed nuclei-templates/http/vulnerabilities/gitlab/gitlab-rce.yaml
//go:embed nuclei-templates/http/vulnerabilities/gradio-image-ssrf.yaml
//go:embed nuclei-templates/http/vulnerabilities/gradio-lfi.yaml
//go:embed nuclei-templates/http/vulnerabilities/gradio/gradio-lfi.yaml
//go:embed nuclei-templates/http/vulnerabilities/gradio/gradio-ssrf.yaml
//go:embed nuclei-templates/http/vulnerabilities/jenkins/jenkins-asyncpeople.yaml
//go:embed nuclei-templates/http/vulnerabilities/jenkins/jenkins-script.yaml
//go:embed nuclei-templates/http/vulnerabilities/jenkins/jenkins-stack-trace.yaml
//go:embed nuclei-templates/http/vulnerabilities/jenkins/unauthenticated-jenkins.yaml
//go:embed nuclei-templates/http/vulnerabilities/jupyter-notebook-rce.yaml
//go:embed nuclei-templates/http/vulnerabilities/other/elasticsearch5-log4j-rce.yaml
//go:embed nuclei-templates/http/vulnerabilities/other/gradio-file-redirect.yaml
//go:embed nuclei-templates/http/vulnerabilities/other/unauth-spark-api.yaml
//go:embed nuclei-templates/http/vulnerabilities/portainer-init-deploy.yaml
var nucleiTemplates embed.FS
