// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveScanSession(arg1) {
  return window['go']['mcpserver']['Service']['ArchiveScanSession'](arg1);
}

export function DeleteScanSession(arg1) {
  return window['go']['mcpserver']['Service']['DeleteScanSession'](arg1);
}

export function GetLocalServerStatus() {
  return window['go']['mcpserver']['Service']['GetLocalServerStatus']();
}

export function GetMCPReport(arg1) {
  return window['go']['mcpserver']['Service']['GetMCPReport'](arg1);
}

export function GetScanSession(arg1) {
  return window['go']['mcpserver']['Service']['GetScanSession'](arg1);
}

export function ListMCPReports(arg1, arg2) {
  return window['go']['mcpserver']['Service']['ListMCPReports'](arg1, arg2);
}

export function ListScanSessions(arg1, arg2) {
  return window['go']['mcpserver']['Service']['ListScanSessions'](arg1, arg2);
}

export function StartLocalServer() {
  return window['go']['mcpserver']['Service']['StartLocalServer']();
}

export function Startup(arg1) {
  return window['go']['mcpserver']['Service']['Startup'](arg1);
}

export function StopLocalServer() {
  return window['go']['mcpserver']['Service']['StopLocalServer']();
}
