// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcpserver} from '../models';
import {context} from '../models';

export function ArchiveScanSession(arg1:mcpserver.ScanSession):Promise<void>;

export function DeleteScanSession(arg1:string):Promise<void>;

export function GetLocalServerStatus():Promise<mcpserver.LocalServerStatus>;

export function GetMCPReport(arg1:string):Promise<mcpserver.MCPReport>;

export function GetScanSession(arg1:string):Promise<mcpserver.ScanSession>;

export function ListMCPReports(arg1:number,arg2:number):Promise<Array<mcpserver.MCPReportMeta>>;

export function ListScanSessions(arg1:number,arg2:number):Promise<Array<mcpserver.ScanSession>>;

export function StartLocalServer():Promise<mcpserver.LocalServerStatus>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopLocalServer():Promise<void>;
