// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cloudscan} from '../models';
import {context} from '../models';

export function GetEngineStatus():Promise<cloudscan.EngineStatus>;

export function Scan(arg1:cloudscan.ScanRequest):Promise<cloudscan.ScanResult>;

export function SelectLocalRepository():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
