// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEngineStatus() {
  return window['go']['main']['AICloudSecurityService']['GetEngineStatus']();
}

export function Scan(arg1) {
  return window['go']['main']['AICloudSecurityService']['Scan'](arg1);
}

export function SelectLocalRepository() {
  return window['go']['main']['AICloudSecurityService']['SelectLocalRepository']();
}

export function Startup(arg1) {
  return window['go']['main']['AICloudSecurityService']['Startup'](arg1);
}
