// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {apitest} from '../models';

export function CheckUpdate(arg1:string):Promise<updater.CheckResult>;

export function Greet(arg1:string):Promise<string>;

export function TestAPIConnection(arg1:apitest.Request):Promise<apitest.Response>;
