// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function GetDashboardStats():Promise<main.DashboardStats>;

export function GetEvaluationReport():Promise<main.EvaluationReportData>;

export function GetRecentTasks(arg1:number):Promise<Array<main.RecentTaskItem>>;

export function GetRiskDistribution():Promise<main.RiskDistItem>;

export function GetTaskTrend(arg1:number):Promise<Array<main.TaskTrendItem>>;

export function Startup(arg1:context.Context):Promise<void>;
