// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboardStats() {
  return window['go']['main']['DashboardService']['GetDashboardStats']();
}

export function GetEvaluationReport() {
  return window['go']['main']['DashboardService']['GetEvaluationReport']();
}

export function GetRecentTasks(arg1) {
  return window['go']['main']['DashboardService']['GetRecentTasks'](arg1);
}

export function GetRiskDistribution() {
  return window['go']['main']['DashboardService']['GetRiskDistribution']();
}

export function GetTaskTrend(arg1) {
  return window['go']['main']['DashboardService']['GetTaskTrend'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['DashboardService']['Startup'](arg1);
}
