// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function CountPrefix(arg1:string):Promise<number>;

export function Delete(arg1:string):Promise<void>;

export function GetString(arg1:string):Promise<string>;

export function ListPrefix(arg1:string,arg2:number,arg3:number):Promise<Array<main.KV>>;

export function OpenAt(arg1:string):Promise<void>;

export function OpenDefault():Promise<void>;

export function OpenForUser(arg1:string):Promise<void>;

export function Path():Promise<string>;

export function PutString(arg1:string,arg2:string):Promise<void>;
