// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {evaluator} from '../models';
import {main} from '../models';
import {context} from '../models';

export function CancelTask(arg1:string):Promise<void>;

export function CountDatasetItems(arg1:evaluator.DatasetConfig):Promise<number>;

export function CountTestItems(arg1:string):Promise<number>;

export function CreateProject(arg1:evaluator.EvalProject):Promise<evaluator.EvalProject>;

export function CreateTask(arg1:evaluator.EvalTask):Promise<evaluator.EvalTask>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function EvaluateScanSteps(arg1:main.ManualScanStepEvaluationRequest):Promise<Array<main.ManualScanStepEvaluationResult>>;

export function GetDatasetFields(arg1:evaluator.DatasetConfig):Promise<Array<main.DatasetFieldInfo>>;

export function GetEvaluatorTemplate(arg1:string):Promise<evaluator.EvaluatorTemplate>;

export function GetProject(arg1:string):Promise<evaluator.EvalProject>;

export function GetRunResult(arg1:string):Promise<evaluator.EvalRunResult>;

export function GetTask(arg1:string):Promise<evaluator.EvalTask>;

export function GetTaskStats(arg1:string):Promise<Record<string, any>>;

export function GetTestItem(arg1:string,arg2:number):Promise<evaluator.TestItem>;

export function ListEvaluatorTemplates():Promise<Array<evaluator.EvaluatorInfo>>;

export function ListProjects(arg1:number,arg2:number):Promise<evaluator.ListResult>;

export function ListTasks(arg1:string,arg2:number,arg3:number):Promise<evaluator.ListResult>;

export function ListTestItems(arg1:string,arg2:number,arg3:number):Promise<evaluator.ListResult>;

export function PauseTask(arg1:string):Promise<void>;

export function ResumeTask(arg1:string):Promise<void>;

export function StartTask(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SyncEvaluatorTemplates():Promise<void>;

export function UpdateProject(arg1:evaluator.EvalProject):Promise<evaluator.EvalProject>;

export function ValidateDatasetConfig(arg1:evaluator.DatasetConfig):Promise<void>;
