// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['main']['EvalService']['CancelTask'](arg1);
}

export function CountDatasetItems(arg1) {
  return window['go']['main']['EvalService']['CountDatasetItems'](arg1);
}

export function CountTestItems(arg1) {
  return window['go']['main']['EvalService']['CountTestItems'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['EvalService']['CreateProject'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['EvalService']['CreateTask'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['EvalService']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['EvalService']['DeleteTask'](arg1);
}

export function EvaluateScanSteps(arg1) {
  return window['go']['main']['EvalService']['EvaluateScanSteps'](arg1);
}

export function GetDatasetFields(arg1) {
  return window['go']['main']['EvalService']['GetDatasetFields'](arg1);
}

export function GetEvaluatorTemplate(arg1) {
  return window['go']['main']['EvalService']['GetEvaluatorTemplate'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['EvalService']['GetProject'](arg1);
}

export function GetRunResult(arg1) {
  return window['go']['main']['EvalService']['GetRunResult'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['EvalService']['GetTask'](arg1);
}

export function GetTaskStats(arg1) {
  return window['go']['main']['EvalService']['GetTaskStats'](arg1);
}

export function GetTestItem(arg1, arg2) {
  return window['go']['main']['EvalService']['GetTestItem'](arg1, arg2);
}

export function ListEvaluatorTemplates() {
  return window['go']['main']['EvalService']['ListEvaluatorTemplates']();
}

export function ListProjects(arg1, arg2) {
  return window['go']['main']['EvalService']['ListProjects'](arg1, arg2);
}

export function ListTasks(arg1, arg2, arg3) {
  return window['go']['main']['EvalService']['ListTasks'](arg1, arg2, arg3);
}

export function ListTestItems(arg1, arg2, arg3) {
  return window['go']['main']['EvalService']['ListTestItems'](arg1, arg2, arg3);
}

export function PauseTask(arg1) {
  return window['go']['main']['EvalService']['PauseTask'](arg1);
}

export function ResumeTask(arg1) {
  return window['go']['main']['EvalService']['ResumeTask'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['EvalService']['StartTask'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['EvalService']['Startup'](arg1);
}

export function SyncEvaluatorTemplates() {
  return window['go']['main']['EvalService']['SyncEvaluatorTemplates']();
}

export function UpdateProject(arg1) {
  return window['go']['main']['EvalService']['UpdateProject'](arg1);
}

export function ValidateDatasetConfig(arg1) {
  return window['go']['main']['EvalService']['ValidateDatasetConfig'](arg1);
}
