// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPortScan(arg1) {
  return window['go']['main']['NucleiService']['CancelPortScan'](arg1);
}

export function CancelScan(arg1) {
  return window['go']['main']['NucleiService']['CancelScan'](arg1);
}

export function GetResult(arg1) {
  return window['go']['main']['NucleiService']['GetResult'](arg1);
}

export function ListRecentRuns(arg1, arg2) {
  return window['go']['main']['NucleiService']['ListRecentRuns'](arg1, arg2);
}

export function ListTemplates() {
  return window['go']['main']['NucleiService']['ListTemplates']();
}

export function ScanPorts(arg1) {
  return window['go']['main']['NucleiService']['ScanPorts'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['NucleiService']['StartScan'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['NucleiService']['Startup'](arg1);
}
