// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nucleiscan} from '../models';
import {context} from '../models';

export function CancelPortScan(arg1:string):Promise<void>;

export function CancelScan(arg1:string):Promise<void>;

export function GetResult(arg1:string):Promise<nucleiscan.ScanResult>;

export function ListRecentRuns(arg1:number,arg2:number):Promise<Array<nucleiscan.ScanResult>>;

export function ListTemplates():Promise<Array<nucleiscan.TemplateInfo>>;

export function ScanPorts(arg1:nucleiscan.PortScanConfig):Promise<nucleiscan.PortScanResult>;

export function StartScan(arg1:nucleiscan.ScanConfig):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
