// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteReport(arg1) {
  return window['go']['main']['ReportService']['DeleteReport'](arg1);
}

export function ExportReport(arg1) {
  return window['go']['main']['ReportService']['ExportReport'](arg1);
}

export function ExportReportAsMarkdown(arg1) {
  return window['go']['main']['ReportService']['ExportReportAsMarkdown'](arg1);
}

export function ExportReportAsPDF(arg1) {
  return window['go']['main']['ReportService']['ExportReportAsPDF'](arg1);
}

export function GenerateReport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['ReportService']['GenerateReport'](arg1, arg2, arg3, arg4, arg5);
}

export function GetReportByID(arg1) {
  return window['go']['main']['ReportService']['GetReportByID'](arg1);
}

export function ListReports() {
  return window['go']['main']['ReportService']['ListReports']();
}

export function Startup(arg1) {
  return window['go']['main']['ReportService']['Startup'](arg1);
}
