// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function DeleteReport(arg1:string):Promise<void>;

export function ExportReport(arg1:string):Promise<void>;

export function ExportReportAsMarkdown(arg1:string):Promise<void>;

export function ExportReportAsPDF(arg1:string):Promise<void>;

export function GenerateReport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Report>;

export function GetReportByID(arg1:string):Promise<main.Report>;

export function ListReports():Promise<Array<main.ReportListItem>>;

export function Startup(arg1:context.Context):Promise<void>;
