// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {samples} from '../models';
import {main} from '../models';
import {scanner} from '../models';

export function CountSamplesForTask(arg1:string):Promise<number>;

export function DeleteCommunityPrompt(arg1:number):Promise<void>;

export function DeleteHfDataset(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteSample(arg1:string):Promise<void>;

export function DeleteSampleSet(arg1:string):Promise<void>;

export function DeleteTaskConfig(arg1:string):Promise<void>;

export function ExtractPlaceholders(arg1:string):Promise<Array<string>>;

export function GenerateSamples(arg1:samples.GenerateRequest):Promise<samples.GenerateResult>;

export function GetHfDatasetMeta(arg1:string,arg2:string,arg3:string):Promise<samples.HfDatasetMeta>;

export function GetHfDatasetRows(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<samples.ListResult>;

export function GetSample(arg1:string):Promise<samples.Sample>;

export function GetSampleSet(arg1:string):Promise<samples.SampleSet>;

export function GetSamplesForTask(arg1:string):Promise<Array<main.UnifiedSample>>;

export function GetSamplesForTaskByConfig(arg1:Array<string>,arg2:Array<string>):Promise<Array<main.UnifiedSample>>;

export function GetTaskDatasetConfig(arg1:string):Promise<main.TaskDatasetConfig>;

export function IsHfDatasetDownloaded(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function ListDownloadedCommunityPrompts():Promise<Array<samples.CommunityPrompt>>;

export function ListDownloadedHfDatasets():Promise<Array<samples.HfDatasetMeta>>;

export function ListSampleSets(arg1:number,arg2:number):Promise<samples.ListResult>;

export function ListSamplesBySet(arg1:string,arg2:number,arg3:number):Promise<samples.ListResult>;

export function LoadSamplesForTask(arg1:string):Promise<Array<scanner.Sample>>;

export function SaveHfDataset(arg1:samples.HfDatasetMeta,arg2:Array<samples.HfDataRow>):Promise<void>;

export function SaveTaskDatasetConfig(arg1:string,arg2:main.TaskDatasetConfig):Promise<void>;

export function SearchSampleSets(arg1:string,arg2:number,arg3:number):Promise<samples.ListResult>;
