// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountSamplesForTask(arg1) {
  return window['go']['main']['SampleService']['CountSamplesForTask'](arg1);
}

export function DeleteCommunityPrompt(arg1) {
  return window['go']['main']['SampleService']['DeleteCommunityPrompt'](arg1);
}

export function DeleteHfDataset(arg1, arg2, arg3) {
  return window['go']['main']['SampleService']['DeleteHfDataset'](arg1, arg2, arg3);
}

export function DeleteSample(arg1) {
  return window['go']['main']['SampleService']['DeleteSample'](arg1);
}

export function DeleteSampleSet(arg1) {
  return window['go']['main']['SampleService']['DeleteSampleSet'](arg1);
}

export function DeleteTaskConfig(arg1) {
  return window['go']['main']['SampleService']['DeleteTaskConfig'](arg1);
}

export function ExtractPlaceholders(arg1) {
  return window['go']['main']['SampleService']['ExtractPlaceholders'](arg1);
}

export function GenerateSamples(arg1) {
  return window['go']['main']['SampleService']['GenerateSamples'](arg1);
}

export function GetHfDatasetMeta(arg1, arg2, arg3) {
  return window['go']['main']['SampleService']['GetHfDatasetMeta'](arg1, arg2, arg3);
}

export function GetHfDatasetRows(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['SampleService']['GetHfDatasetRows'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSample(arg1) {
  return window['go']['main']['SampleService']['GetSample'](arg1);
}

export function GetSampleSet(arg1) {
  return window['go']['main']['SampleService']['GetSampleSet'](arg1);
}

export function GetSamplesForTask(arg1) {
  return window['go']['main']['SampleService']['GetSamplesForTask'](arg1);
}

export function GetSamplesForTaskByConfig(arg1, arg2) {
  return window['go']['main']['SampleService']['GetSamplesForTaskByConfig'](arg1, arg2);
}

export function GetTaskDatasetConfig(arg1) {
  return window['go']['main']['SampleService']['GetTaskDatasetConfig'](arg1);
}

export function IsHfDatasetDownloaded(arg1, arg2, arg3) {
  return window['go']['main']['SampleService']['IsHfDatasetDownloaded'](arg1, arg2, arg3);
}

export function ListDownloadedCommunityPrompts() {
  return window['go']['main']['SampleService']['ListDownloadedCommunityPrompts']();
}

export function ListDownloadedHfDatasets() {
  return window['go']['main']['SampleService']['ListDownloadedHfDatasets']();
}

export function ListSampleSets(arg1, arg2) {
  return window['go']['main']['SampleService']['ListSampleSets'](arg1, arg2);
}

export function ListSamplesBySet(arg1, arg2, arg3) {
  return window['go']['main']['SampleService']['ListSamplesBySet'](arg1, arg2, arg3);
}

export function LoadSamplesForTask(arg1) {
  return window['go']['main']['SampleService']['LoadSamplesForTask'](arg1);
}

export function SaveHfDataset(arg1, arg2) {
  return window['go']['main']['SampleService']['SaveHfDataset'](arg1, arg2);
}

export function SaveTaskDatasetConfig(arg1, arg2) {
  return window['go']['main']['SampleService']['SaveTaskDatasetConfig'](arg1, arg2);
}

export function SearchSampleSets(arg1, arg2, arg3) {
  return window['go']['main']['SampleService']['SearchSampleSets'](arg1, arg2, arg3);
}
