// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan(arg1) {
  return window['go']['main']['ScannerService']['CancelScan'](arg1);
}

export function CountActiveRuns() {
  return window['go']['main']['ScannerService']['CountActiveRuns']();
}

export function CountFailedSteps(arg1) {
  return window['go']['main']['ScannerService']['CountFailedSteps'](arg1);
}

export function GetFailedSteps(arg1) {
  return window['go']['main']['ScannerService']['GetFailedSteps'](arg1);
}

export function GetRunSummary(arg1) {
  return window['go']['main']['ScannerService']['GetRunSummary'](arg1);
}

export function GetTaskStats(arg1) {
  return window['go']['main']['ScannerService']['GetTaskStats'](arg1);
}

export function ListRecentRuns(arg1, arg2) {
  return window['go']['main']['ScannerService']['ListRecentRuns'](arg1, arg2);
}

export function ListRunSteps(arg1, arg2, arg3) {
  return window['go']['main']['ScannerService']['ListRunSteps'](arg1, arg2, arg3);
}

export function ListTaskRuns(arg1, arg2, arg3) {
  return window['go']['main']['ScannerService']['ListTaskRuns'](arg1, arg2, arg3);
}

export function RetryFailedRequests(arg1) {
  return window['go']['main']['ScannerService']['RetryFailedRequests'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['ScannerService']['StartScan'](arg1);
}

export function StartScanForTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ScannerService']['StartScanForTask'](arg1, arg2, arg3, arg4);
}

export function Startup(arg1) {
  return window['go']['main']['ScannerService']['Startup'](arg1);
}
