// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';
import {main} from '../models';
import {context} from '../models';

export function CancelScan(arg1:string):Promise<void>;

export function CountActiveRuns():Promise<number>;

export function CountFailedSteps(arg1:string):Promise<number>;

export function GetFailedSteps(arg1:string):Promise<Array<scanner.StepResult>>;

export function GetRunSummary(arg1:string):Promise<scanner.RunResult>;

export function GetTaskStats(arg1:string):Promise<main.TaskStats>;

export function ListRecentRuns(arg1:number,arg2:number):Promise<Array<scanner.RunResult>>;

export function ListRunSteps(arg1:string,arg2:number,arg3:number):Promise<Array<scanner.StepResult>>;

export function ListTaskRuns(arg1:string,arg2:number,arg3:number):Promise<Array<scanner.RunResult>>;

export function RetryFailedRequests(arg1:string):Promise<string>;

export function StartScan(arg1:scanner.RunConfig):Promise<string>;

export function StartScanForTask(arg1:string,arg2:scanner.RequestSpec,arg3:Array<scanner.Sample>,arg4:Record<string, string>):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
