// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyTestCase(arg1) {
  return window['go']['main']['TestCaseService']['CopyTestCase'](arg1);
}

export function CreateTestCase(arg1) {
  return window['go']['main']['TestCaseService']['CreateTestCase'](arg1);
}

export function CreateVariable(arg1) {
  return window['go']['main']['TestCaseService']['CreateVariable'](arg1);
}

export function DeleteTestCase(arg1) {
  return window['go']['main']['TestCaseService']['DeleteTestCase'](arg1);
}

export function DeleteVariable(arg1) {
  return window['go']['main']['TestCaseService']['DeleteVariable'](arg1);
}

export function GetTestCase(arg1) {
  return window['go']['main']['TestCaseService']['GetTestCase'](arg1);
}

export function GetVariable(arg1) {
  return window['go']['main']['TestCaseService']['GetVariable'](arg1);
}

export function ListTestCases(arg1, arg2) {
  return window['go']['main']['TestCaseService']['ListTestCases'](arg1, arg2);
}

export function ListVariables(arg1, arg2) {
  return window['go']['main']['TestCaseService']['ListVariables'](arg1, arg2);
}

export function ToggleTestCaseStatus(arg1) {
  return window['go']['main']['TestCaseService']['ToggleTestCaseStatus'](arg1);
}

export function ToggleVariableEnabled(arg1) {
  return window['go']['main']['TestCaseService']['ToggleVariableEnabled'](arg1);
}

export function UpdateTestCase(arg1) {
  return window['go']['main']['TestCaseService']['UpdateTestCase'](arg1);
}

export function UpdateVariable(arg1) {
  return window['go']['main']['TestCaseService']['UpdateVariable'](arg1);
}
