// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyTestCase(arg1:string):Promise<main.TestCase>;

export function CreateTestCase(arg1:main.TestCase):Promise<main.TestCase>;

export function CreateVariable(arg1:main.UserVariable):Promise<main.UserVariable>;

export function DeleteTestCase(arg1:string):Promise<void>;

export function DeleteVariable(arg1:string):Promise<void>;

export function GetTestCase(arg1:string):Promise<main.TestCase>;

export function GetVariable(arg1:string):Promise<main.UserVariable>;

export function ListTestCases(arg1:number,arg2:number):Promise<main.ListResult>;

export function ListVariables(arg1:number,arg2:number):Promise<main.ListResult>;

export function ToggleTestCaseStatus(arg1:string):Promise<main.TestCase>;

export function ToggleVariableEnabled(arg1:string):Promise<main.UserVariable>;

export function UpdateTestCase(arg1:main.TestCase):Promise<main.TestCase>;

export function UpdateVariable(arg1:main.UserVariable):Promise<main.UserVariable>;
