// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['YamlScanService']['ClearHistory']();
}

export function DeleteHistory(arg1) {
  return window['go']['main']['YamlScanService']['DeleteHistory'](arg1);
}

export function FetchFromGitHub(arg1) {
  return window['go']['main']['YamlScanService']['FetchFromGitHub'](arg1);
}

export function GetBuiltinRules() {
  return window['go']['main']['YamlScanService']['GetBuiltinRules']();
}

export function GetResult(arg1) {
  return window['go']['main']['YamlScanService']['GetResult'](arg1);
}

export function ListHistory(arg1, arg2) {
  return window['go']['main']['YamlScanService']['ListHistory'](arg1, arg2);
}

export function ScanYAML(arg1) {
  return window['go']['main']['YamlScanService']['ScanYAML'](arg1);
}
