// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {yamlscan} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteHistory(arg1:string):Promise<void>;

export function FetchFromGitHub(arg1:string):Promise<string>;

export function GetBuiltinRules():Promise<Array<yamlscan.Rule>>;

export function GetResult(arg1:string):Promise<yamlscan.ScanResult>;

export function ListHistory(arg1:number,arg2:number):Promise<Array<yamlscan.ScanHistory>>;

export function ScanYAML(arg1:yamlscan.ScanRequest):Promise<yamlscan.ScanResult>;
